Updated all assets to new compressed versions
filecoin-project/slate pull request #224
Opened 2020-09-07 12:41 UTC by gndclouds

What changed:
- Images and videos are about 50% smaller, 
- Added images previews to example slates. 

Would love feedback on if there is a better way to implement lines **412** to **510**. It feels like, I could have wrapped each card element in one more `div` to make the CSS classes less repetitive but not sure if one way is better for performance over the other. 🤷🏻‍♂️ LMK!

2020-09-07 12:44 UTC, gndclouds commented
Also, the [Slate/Marketing](https://slate.host/slate/marketing) is a little messy, I can remove the duplicates once this is merged and pushed to production. (Didn't want to anything currently being used) Currently, updated files are marked with _-small_ .

2020-09-07 18:08 UTC, jimmylee requested changes

2020-09-07 18:08 UTC, jimmylee commented on pages/index.js
> +                <div css={STYLES_SLATE_CARD_URBAN_GARDENS}>
There is a lot of code duplication here, we may want to create a:

```
SOME_CONSTANT_SET.map(each => {
   return (<div>Hello World</div>);
});
```

2020-09-09 10:41 UTC, gndclouds commented
almost have the array.map working.

2020-09-09 19:44 UTC, merged