[WIP] @gndclouds/community will
filecoin-project/slate pull request #309
Opened 2020-09-20 04:17 UTC by gndclouds

Started to apply community page styles form design channel feedback.

2020-09-20 16:02 UTC, jimmylee requested changes

2020-09-20 16:02 UTC, jimmylee commented on components/core/CodeTerminal.js
> +0% {opacity: 0;}
nit: formatting

2020-09-20 16:02 UTC, jimmylee commented on components/core/CodeTerminal.js
> +
extra whitespace

2020-09-20 16:02 UTC, jimmylee commented on components/core/CodeTerminal.js
> +const STYLES_WINDOW_BODY = css`
new line

2020-09-20 23:35 UTC, gndclouds commented
thanks for catching those! I only meant to submit the community-w so I hadn't checked that file yet.

2020-09-22 00:42 UTC, jimmylee requested changes
Almost :)

2020-09-22 00:42 UTC, jimmylee commented on components/core/CodeTerminal.js
> +
```
const blinkCursor = keyframes`
  0% {opacity: 0;}
  50% {opacity: 1;}
  100% {opacity: 0;}
`;
```

2020-09-22 00:42 UTC, jimmylee commented on components/core/CodeTerminal.js
> +`;
```
const typewriter = keyframes`
  0%, 100% {width: 0;}
  20%, 80% {width: 10.2em;}
`;
```

2020-09-22 00:42 UTC, jimmylee commented on components/core/CodeTerminal.js
> +        <div css={STYLES_WINDOW_NAV}>Cat</div>
What does Cat mean? Sounds fun :)

2020-09-22 01:22 UTC, gndclouds commented on components/core/CodeTerminal.js
> +        <div css={STYLES_WINDOW_NAV}>Cat</div>
Ha was testing the component ;-)

2020-09-22 01:33 UTC, merged