WIP @gndclouds/data bar breakdown
filecoin-project/slate pull request #397
Opened 2020-10-30 14:20 UTC by gndclouds

Need to check in with Haris on colors.

2020-11-01 05:34 UTC, gndclouds commented
@jimmylee and @martinalong There is a CSS issue I'm having trouble finding. The DataMeterBars are stacked on top of one another (largest to smallest). But the `background-color` for each DataMeterBar is always being applied to the largest bar. I added two new props to the react fragment one for the `background-color` and one for the `z-index`.

[New props:](https://github.com/filecoin-project/slate/blob/af62ab2670a4922783baa74ab95d8954adeeda24/components/core/DataMeter.js#L199)
```html
<DataMeterBar
     bytes={props.stats.imageBytes}
     maximumBytes={props.stats.maximumBytes}
     dataMeterColor={`#C0DACD`}
     dataMeterLayer={`5`}
  />
```

[Passing props into fragment](https://github.com/filecoin-project/slate/blob/af62ab2670a4922783baa74ab95d8954adeeda24/components/core/DataMeter.js#L142): 

```html
<div
          css={STYLES_DATA_METER}
          style={{
            width: `${percentage * 100}%`,
            backgroundColor: props.dataMeterColor,
            zIndex: props.dataMeterLayer,
          }}
        ></div>
      </div>
```

I feel like I must be misunderstanding something with how react renders fragments because this should be really straight forward.

2020-11-04 07:13 UTC, jimmylee requested changes
Would be nice for you to do the inline-flex element strategy instead. Then these elements wouldn't need to overlap.

2020-11-04 07:13 UTC, jimmylee commented on components/core/DataMeter.js
> +  top: 0px;
I don't think the data meter needs to be an absolutely positioned component.

2020-11-04 07:13 UTC, jimmylee commented on components/core/DataMeter.js
> +const STYLES_DATA_METER_KEY_SQUARE = css`
New line

2020-11-04 07:13 UTC, jimmylee commented on components/core/DataMeter.js
> +const STYLES_DATA_METER_KEY_LABEL = css`
New line

2020-11-04 07:13 UTC, jimmylee commented on components/core/DataMeter.js
> +        <DataMeterBar
I think the strategy should be inline-flex elements like the codepen I posted earlier: https://codepen.io/meanjim/pen/pobKKbr

2020-11-04 14:55 UTC, gndclouds commented
Sorry for the confusion, I created a new component called DataMeterDetail for the Data page. Since the DataMeter is used elsewhere I did not want to alter it. This PR is not correct and uses the Flex implementation.

2020-11-04 22:07 UTC, jimmylee commented
> This PR is not correct and uses the Flex implementation.

What does this mean?

Also I want to be clear that you can create new components. I'm just saying the `position: absolute` implementation is incorrect, take the slower pace we are moving at right now to make sure you learn the other implementation.

2020-11-04 22:09 UTC, jimmylee commented
Branches that have new feature work should be accompanied by a screenshot or preview link as well. You can build these components without integrating with data so take that into consideration.

2020-11-07 03:30 UTC, jimmylee commented on components/core/DataMeterDetailed.js
> +const STYLES_DATA_METER_KEY_SQUARE = css`
new line.

2020-11-07 03:30 UTC, jimmylee commented on components/core/DataMeterDetailed.js
> +const STYLES_DATA_METER_KEY_LABEL = css`
new line

2020-11-07 03:30 UTC, jimmylee commented on components/core/DataMeterDetailed.js
> +  console.log(percentageImage);
remove the console log

2020-11-07 03:31 UTC, jimmylee requested changes
Looks good! Tried it out, please fixes these nits and we can get this landed.

2020-11-07 03:31 UTC, jimmylee commented on components/core/DataMeterDetailed.js
> +export const DataMeter = (props) => {
DataMeterDetailed

2020-11-07 03:31 UTC, jimmylee commented on components/core/DataMeterDetailed.js
> +export default DataMeter;
DataMeterDetailed

2020-11-07 08:33 UTC, jimmylee approved these changes
LGTM

2020-11-07 08:33 UTC, merged